# Uncomment the next line to define a global platform for your project
platform :osx, '11.0'

target 'LilyPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LilyPod
  pod 'ffmpeg-kit-macos-min-gpl', '~> 4.4.LTS'
end
